name: code-quality
recipe: lamp
config:
  php: '8.1'
  xdebug: true

services:
  appserver:
    build:
      - composer install

tooling:
  phpunit:
    service: appserver
    description: Run Drupal PHPUnit tests. Run 'lando phpunit --help' for more information.
    cmd:
      - "/app/.lando/tooling-phpunit.sh"
  grumphp:
    service: appserver
    description: Runs grumphp commands
    cmd: /app/.lando/tooling-grumphp.sh
