services:
   Wunderio\GrumPHP\Task\Ecs\EcsTask:
    class: Wunderio\GrumPHP\Task\Ecs\EcsTask
    arguments:
      - '@process_builder'
      - '@formatter.raw_process'
    tags:
      - {name: grumphp.task, task: ecs}
