grumphp:
  stop_on_failure: true
  process_timeout: 300
  ascii:
    failed: ~
    succeeded: ~
  tasks:
    php_compatibility: ~
    check_file_permissions: ~
    php_check_syntax: ~
    phpcs: ~
    php_stan: ~
    yaml_lint: ~
    json_lint: ~
    psalm: ~
    eslint: ~
  extensions:
    - Wunderio\GrumPHP\Task\PhpCompatibility\PhpCompatibilityExtensionLoader
    - Wunderio\GrumPHP\Task\PhpCheckSyntax\PhpCheckSyntaxExtensionLoader
    - Wunderio\GrumPHP\Task\CheckFilePermissions\CheckFilePermissionsExtensionLoader
    - Wunderio\GrumPHP\Task\Ecs\EcsExtensionLoader
    - Wunderio\GrumPHP\Task\Phpcs\PhpcsExtensionLoader
    - Wunderio\GrumPHP\Task\PhpStan\PhpStanExtensionLoader
    - Wunderio\GrumPHP\Task\YamlLint\YamlLintExtensionLoader
    - Wunderio\GrumPHP\Task\JsonLint\JsonLintExtensionLoader
    - Wunderio\GrumPHP\Task\Psalm\PsalmExtensionLoader
    - Wunderio\GrumPHP\Task\ESLint\EslintExtensionLoader
